version: '2'

services:

  es:
    build: es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.7
    environment:
      ELASTICSEARCH_URL: "http://es:9200"
    ports:
      - 5601:5601
